version: "3.8"
services:
  web:
    build: ./web/
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_USER: niits
      POSTGRES_DB: page
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080